---
# tasks file for aap_backup

#
# -----------------------------------------------------------------------------
# Prepare for AAP work
# -----------------------------------------------------------------------------
#

- include_tasks: backup.yml
  tags:
    - backup
...
